server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Qualquer requisição para o Nginx que não for um arquivo real,
    # ele redireciona para o index.html. Isso é crucial para o Roteamento do Angular (SPA).
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache opcional para arquivos estáticos (melhora performance)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
